# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-10-03 11:04+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"

#. pylint: disable-next=consider-using-f-string
#: ../src/up2date_client/config.py:166
#, python-format
msgid "%s was not found"
msgstr ""

#: ../src/up2date_client/rpcServer.py:70
msgid "Error: Server Unavailable. Please try later."
msgstr ""

#. pylint: disable-next=consider-using-f-string
#: ../src/up2date_client/rpcServer.py:221
msgid "ERROR: can not find server CA file"
msgstr ""

#: ../src/up2date_client/up2dateErrors.py:62
#: ../src/up2date_client/up2dateErrors.py:101
#, python-format
msgid "class %s has no attribute '%s'"
msgstr ""

#: ../src/up2date_client/up2dateErrors.py:135
msgid "RPM error.  The message was:\n"
msgstr ""

#: ../src/up2date_client/up2dateErrors.py:145
msgid "Password error. The message was:\n"
msgstr ""

#: ../src/up2date_client/up2dateErrors.py:151
msgid "RPM dependency error. The message was:\n"
msgstr ""

#: ../src/up2date_client/up2dateErrors.py:163
msgid "Error communicating with server. The message was:\n"
msgstr ""

#: ../src/up2date_client/up2dateErrors.py:172
msgid "File Not Found: \n"
msgstr ""

#: ../src/up2date_client/up2dateErrors.py:180
msgid "Delay error from server.  The message was:\n"
msgstr ""

#: ../src/up2date_client/up2dateErrors.py:229
msgid "Error validating data at server:\n"
msgstr ""

#: ../src/up2date_client/up2dateErrors.py:246
msgid ""
"\n"
"Red Hat Network Classic is not supported.\n"
"    "
msgstr ""

#: ../src/up2date_client/up2dateErrors.py:255
msgid "The installation number is invalid"
msgstr ""

#: ../src/up2date_client/up2dateErrors.py:259
msgid "Error parsing the oemInfo file at field:\n"
msgstr ""

#: ../src/up2date_client/up2dateErrors.py:294
msgid "Network error: "
msgstr ""

#: ../src/up2date_client/up2dateErrors.py:385
msgid ""
"\n"
"    Your organization does not have enough Management entitlements to "
"register this\n"
"    system. Please notify your organization administrator of this error.\n"
"    You should be able to register this system after your organization frees "
"existing\n"
"    or purchases additional entitlements. Additional entitlements may be "
"purchased by your\n"
"    organization administrator in the SUSE Customer Center.\n"
"\n"
"    A common cause of this error code is due to having mistakenly setup an\n"
"    Activation Key which is set as the universal default.  If an activation "
"key is set\n"
"    on the account as a universal default, you can disable this key and "
"retry to avoid\n"
"    requiring a Management entitlement."
msgstr ""
